---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: beryl
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/kinoite-main
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: os-release
    properties:
      ID: beryl
      ID_LIKE: fedora
      NAME: Beryl
      PRETTY_NAME: Beryl Image
      HOME_URL: "https://github.com/lamancha/beryl"
  
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    repos:
      - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
      - https://copr.fedorainfracloud.org/coprs/rok/cdemu/repo/fedora-%OS_VERSION%/rok-cdemu-fedora-%OS_VERSION%.repo # when including COPR repos, use the %OS_VERSION% magic string
      - https://copr.fedorainfracloud.org/coprs/lilay/topgrade/repo/fedora-%OS_VERSION%/lilay-topgrade-fedora-%OS_VERSION%.repo # when including COPR repos, use the %OS_VERSION% magic string
      - https://download.docker.com/linux/fedora/docker-ce.repo
    install:
      - akmods
      - apptainer
      - bcachefs-tools
      - containerd.io
      - cups-pdf
      - distrobox
      - docker-ce
      - docker-ce-cli
      - docker-buildx-plugin
      - docker-compose-plugin
      - duf
      - elvish
      - fish
      - fzf
      - git
      - kernel-devel
      - kitty
      - kitty-shell-integration
      - mc
      - micro
      - neovim
      - ripgrep
      - tailscale
      - topgrade
      - wget1
      - wget1-wget
    remove:
      # example: removing firefox (in favor of the flatpak)
      # "firefox" is the main package, "firefox-langpacks" is a dependency
      - firefox
      - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)
      - wget2-wget

  - type: akmods
    base: main
    install:
      - xone
  
  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install:
          - com.github.tchx84.Flatseal
          - one.ablaze.floorp
          # - it.mijorus.gearlever
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system # workaround for gnome error in bluebuild flatpak service
        repo:
          title: fedora
          url: oci+https://registry.fedoraproject.org
        install:
          - org.kde.krdc
          - org.kde.okular
          - org.kde.elisa
          - org.kde.gwenview
          - org.kde.kcalc
          - org.kde.kmahjongg
          - org.kde.kmines
          - org.kde.kolourpaint
          - org.kde.skanpage

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

  - type: brew
    nofile-limits: true # increase nofile limits
    brew-analytics: false # disable telemetry
  
  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode # don't add spaces or "Nerd Font" suffix.
        - Hack
        - JetBrainsMono
        - NerdFontsSymbolsOnly
